### ISSUE TITLE
Error in data loading

### ISSUE THREAD

**Issue by bioannidis** [snap-stanford/pretrain-gnns#1]
Hi,

Thanks for providing the code.
I get an error in the pretrain_contextpred.py
at:
##############
for step, batch in enumerate(tqdm(loader, desc="Iteration")):
#########
error reads as
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 188, in __getitem__
    data = self.get(self.indices()[idx])
  File "/Users/ivasilei/PycharmProjects/UniversalEmbedding/aux_files/pretrain-gnns-master/chem/loader.py", line 298, in get
    slices[idx + 1])
AttributeError: 'Data' object has no attribute 'cat_dim'

Any ideas regarding this?

Thanks, Vassilis

**Comment by weihua916** [comment]
Hi,
Thank you for the interest. The error is most likely due to the Pytorch Geometric version. Did you use the specified version?
