### ISSUE TITLE
Shape mismatch error when switching the model to GAT

### ISSUE THREAD

**Issue by Yujun-Yan** [snap-stanford/pretrain-gnns#40]
Hi, I got shape mismatch error for this line "x_j += edge_attr" in the message function of GATConv class when I tried to switch to the GAT model. It seems that the reshaping "x = self.weight_linear(x).view(-1, self.heads, self.emb_dim)"  in the forward function mess up the shape of "x_j".

**Comment by wubo2180** [comment]
You may change  `x = self.weight_linear(x).view(-1, self.heads, self.emb_dim)` to `x = self.weight_linear(x)`. And add `x_i=x_i.view(-1, self.heads, self.emb_dim)`,`x_j=x_j.view(-1, self.heads, self.emb_dim)` in function `def message(self, edge_index, x_i, x_j, edge_attr):`.

**Comment by kajjana** [comment]
I change the code as you described but I still get this error.


Traceback (most recent call last):
  File "attribute_masking.py", line 784, in <module>
    main()
  File "attribute_masking.py", line 778, in main
    train_loss, train_acc_atom, train_acc_bond = train(mask_edge, model_list, loader, optimizer_list, device)
  File "attribute_masking.py", line 699, in train
    node_rep = model(batch.x, batch.edge_index, batch.edge_attr)
  File "/home/programs/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "attribute_masking.py", line 276, in forward
    h = self.gnns[layer](h_list[layer], edge_index, edge_attr)
  File "/home/programs/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "attribute_masking.py", line 157, in forward
    return self.propagate(edge_index[0], x=x, edge_attr=edge_embeddings)
  File "/home/programs/conda/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 344, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/home/programs/conda/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 428, in aggregate
    reduce=self.aggr)
  File "/home/programs/conda/lib/python3.7/site-packages/torch_scatter/scatter.py", line 152, in scatter
    return scatter_sum(src, index, dim, out, dim_size)
  File "/home/programs/conda/lib/python3.7/site-packages/torch_scatter/scatter.py", line 11, in scatter_sum
    index = broadcast(index, src, dim)
  File "/home/programs/conda/lib/python3.7/site-packages/torch_scatter/utils.py", line 12, in broadcast
    src = src.expand(other.size())
RuntimeError: The expanded size of the tensor (2) must match the existing size (2918) at non-singleton dimension 1.  Target sizes: [2918, 2, 300].  Tensor sizes: [1, 2918, 1]

**Comment by chao1224** [comment]
@kajjana 
This can be fixed by setting `self.node_dim=0` in GATConv.
