### ISSUE TITLE
Fine-tuning on a new dataset. 

### ISSUE THREAD

**Issue by SejeongPark8354** [snap-stanford/pretrain-gnns#56]
I tried to fine-tuning using pretrained GIN. 
But, there were errors during forward in GIN. 

when I run below code (GINConv), 
```
    def forward(self, x, edge_index, edge_attr):
        #add self loops in the edge space
        print(x.size(0))
        print(edge_index)
        print(edge_index.type)
        print(edge_index.shape)
        edge_index = add_self_loops(edge_index, num_nodes = x.size(0))
        #add features corresponding to self-loop edges.
        self_loop_attr = torch.zeros(x.size(0), 2)
        self_loop_attr[:,0] = 4 #bond type for self-loop edge
        self_loop_attr = self_loop_attr.to(edge_attr.device).to(edge_attr.dtype)
        edge_attr = torch.cat((edge_attr, self_loop_attr), dim = 0)

        edge_embeddings = self.edge_embedding1(edge_attr[:,0]) + self.edge_embedding2(edge_attr[:,1])

        print(edge_index)
        return self.propagate(self.aggr, edge_index, x=x, edge_attr=edge_embeddings)

```
I got the command line error like below. 

1076
tensor([[   0,    1,    1,  ..., 1060, 1075, 1070],
        [   1,    0,    2,  ..., 1066, 1070, 1075]], device='cuda:0')
<built-in method type of Tensor object at 0x7f4529fd7280>
torch.Size([2, 2312])
(tensor([[   0,    1,    1,  ..., 1073, 1074, 1075],
        [   1,    0,    2,  ..., 1073, 1074, 1075]], device='cuda:0'), None)
Iteration:   0%|                                                        | 0/1360 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "finetune.py", line 268, in <module>
    main()
  File "finetune.py", line 223, in main
    train(args, model, device, train_loader, optimizer)
  File "finetune.py", line 34, in train
    pred = model(batch.x, batch.edge_index, batch.edge_attr, batch.batch)
  File "/home/sejeong/anaconda3/envs/aigen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sejeong/codes/pretrain-gnns/chem/model.py", line 373, in forward
    node_representation = self.gnn(x, edge_index, edge_attr)
  File "/home/sejeong/anaconda3/envs/aigen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sejeong/codes/pretrain-gnns/chem/model.py", line 272, in forward
    h = self.gnns[layer](h_list[layer], edge_index, edge_attr)
  File "/home/sejeong/anaconda3/envs/aigen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sejeong/codes/pretrain-gnns/chem/model.py", line 53, in forward
    return self.propagate(self.aggr, edge_index, x=x, edge_attr=edge_embeddings)
  File "/home/sejeong/anaconda3/envs/aigen/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 329, in propagate
    size = self.__check_input__(edge_index, size)
  File "/home/sejeong/anaconda3/envs/aigen/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 213, in __check_input__
    raise ValueError(
ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.

The None value was added after add_self_loops. 
Could you explain to me why this was happened? 

+I tried this with tox21 dataset and then the same error was also occurred. 
What am I doing wrong?

**Comment by SejeongPark8354** [comment]
This problem was caused by torch_geometric version difference. It has now been resolved.

**Comment by leibohan** [comment]
which version worked in the end?
