### ISSUE TITLE
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

### ISSUE THREAD

**Issue by zwangeo** [snap-stanford/pretrain-gnns#59]
I was utilizing the latest version of python-geometric 2.X to achieve some latest implementations. When I was handling the Bio dataset processed by the older version of PyG (1.X), this error occurs. I'd like to inquire, is there a way that I can handle the data without degrading the PyG version to 1.X (since some lastest implementations in 2.X is really needed)? The following is the full traceback. Many thanks!!

Traceback (most recent call last):
  File "/export/data/zhili/projects/4th/ours/pretrain-gnns/bio/finetune.py", line 253, in <module>
    main()
  File "/export/data/zhili/projects/4th/ours/pretrain-gnns/bio/finetune.py", line 178, in main
    trainval_dataset, test_dataset = species_split(dataset)
  File "/export/data/zhili/projects/4th/ours/pretrain-gnns/bio/splitters.py", line 66, in species_split
    train_valid_dataset = dataset[train_valid_byte_tensor.tolist()]
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 263, in __getitem__
    return self.index_select(idx)
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 298, in index_select
    dataset = copy.copy(self)
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/copy.py", line 92, in copy
    rv = reductor(4)
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/in_memory_dataset.py", line 168, in __getattr__
    if isinstance(data, Data) and key in data:
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/data.py", line 145, in __contains__
    return key in self.keys
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/data.py", line 134, in keys
    for store in self.stores:
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/data.py", line 499, in stores
    return [self._store]
  File "/export/data/zhili/anaconda3/envs/fourth/lib/python3.9/site-packages/torch_geometric/data/data.py", line 436, in __getattr__
    raise RuntimeError(
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.

**Comment by Suasy** [comment]
so how to fix

**Comment by imk-asyk** [comment]
@Suasy remove the default prrocessed data or change the dir name of 'processed' folder of your dataset
